### ISSUE TITLE
Design project discovery home

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/liquid-funding#10]
Testing Figma integration

**Comment by hesterbruikman** [comment]
[https://www.figma.com/file/DarCEnDHTNmiK1XAjj0IeSY8/DAO-project-discovery?node-id=2%3A3](https://www.figma.com/file/DarCEnDHTNmiK1XAjj0IeSY8/DAO-project-discovery?node-id=2%3A3)

**Comment by bgits** [comment]
> https://www.figma.com/file/DarCEnDHTNmiK1XAjj0IeSY8/DAO-project-discovery?node-id=2%3A3
> 
> > <img alt="" width="48" src="/file/DarCEnDHTNmiK1XAjj0IeSY8/thumbnail?ver=thumbnails/469ec237-da5c-4df6-aee3-1087dc43afcb"><img alt="" height="14" src="https://camo.githubusercontent.com/182118ffb1744c82994ec4536d9c9bed3bc90217/68747470733a2f2f7374617469632e6669676d612e636f6d2f6170702f69636f6e2f312f66617669636f6e2e737667"> Figma**[Figma](https://www.figma.com/file/DarCEnDHTNmiK1XAjj0IeSY8/DAO-project-discovery)**Created with Figma

Seeing a broken link on my end
