### ISSUE TITLE
Title validation

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/liquid-funding#104]
# Problem
Title allows including punctuation which is not allowed in public channel names.

## Expected behavior
Title field only allows characters that can be used to create public channel, OR characters are omitted when generating public channel name.

## Current behavior
Title field allows punctuation characters that cannot be used to create valid public channel.

**Comment by bgits** [comment]
This version fixes this: https://cloudflare-ipfs.com/ipfs/QmTw3GiH2FWA4YbsVJqveE6m9DfJKHkaRLyPWhMMg7D6oE/#/
