### ISSUE TITLE
Checkbox behavior in withdraw flow (one)

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/liquid-funding#107]
# Problem
After transaction is confirmed to `Submit for withdrawal` the check box of the withdrawn funding becomes unchecked while the `Select all` check box is still checked.

## Expected behavior
When any of the list items in the withdrawal view are unchecked, `Select all` checkbox should also be unchecked.

## Current behavior
When item is unchecked after withdrawal, `Select all` remains checked.

**Comment by bgits** [comment]
This is fixed in this version: https://cloudflare-ipfs.com/ipfs/QmXk77Uj4WBtLqCJzzdq72UMjb16qL8Wb2C9SnriFpfZxv/#/
