### ISSUE TITLE
 Checkbox behavior in withdraw flow (two)

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/liquid-funding#108]
# Problem
When a fund has already been withdrawn it can still be selected to `Submit for withdrawal`

## Expected behavior
When a fund has been `Paid` the checkbox to select this item should be in a disabled state.

## Current behavior
When a fund has been `Paid` the checkbox to select this item can still be selected.

**Comment by bgits** [comment]
This is fixed in this version: https://cloudflare-ipfs.com/ipfs/QmXk77Uj4WBtLqCJzzdq72UMjb16qL8Wb2C9SnriFpfZxv/#/
